IntegerArrayChromosome class
giacomelli/GeneticSharp pull request #108
Opened 2023-04-10 18:04 UTC by mihakralj

to preserve bits, this class accepts only positive int[] values and auto-calculate the total bits required.

2023-04-10 18:45 UTC, mihakralj commented
the failed unit test has nothing to do with my contributed code...

2023-04-25 08:36 UTC, AnakinCN commented
Gene<T> is the future

2024-03-21 10:13 UTC, giacomelli requested changes
Please, add unit tests to validate this new class. 
Take a look at https://github.com/giacomelli/GeneticSharp/wiki/unit-tests

2025-02-18 11:07 UTC, giacomelli requested changes
Please, add unit tests for the `IntegerArrayChromosome`.

2025-11-13 10:46 UTC, giacomelli commented
Closing due to inactivity.

Feel free to add unit tests for the IntegerArrayChromosome and reopen the PR.

2025-11-13 10:46 UTC, closed without merging